site_name: Medical Insurance API Docs
theme:
  name: material

nav:
  - Home: index.md
  - API Overview: api_overview.md
  - Endpoints:
      - Patient Info & Eligibility: endpoints/patient_info_and_eligibility.md
      - Prevalidation: endpoints/prevalidation.md
      - Claim Submission: endpoints/submit_claim.md
      - Get All Claims: endpoints/get_all_claims.md
      - Get Claim by UUID: endpoints/get_claim_by_uuid.md
      - Medicine List: endpoints/medicine_list.md
      - Package List: endpoints/package_list.md
  - Models: models.md

plugins:
  - search
  - swagger-ui-tag

