site_name: Medical Insurance API Docs
theme:
  name: material

nav:
  - Home: index.md
  - API Overview: api_overview.md
  - Endpoints:
      - Patient Info & Eligibility: patient_info_and_eligibility.md
      - Prevalidation: prevalidation.md
      - Claim Submission: submit_claim.md
      - Get All Claims: get_all_claims.md
      - Get Claim by UUID: get_claim_by_uuid.md
      - Medicine List: medicines.md
      - Package List: packages.md
  # - Models: models.md

plugins:
  - search


